name = "UsefulFunctions"
uuid = "3faa5a7b-8411-4986-9283-d50561d89da5"
version = "0.1.0"
authors = ["biplab "]

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
LinearAlgebra = "1.12.0"
Test = "1.11.0"
